### ISSUE TITLE
Modifying a resource trying to add a photo fails

### ISSUE THREAD

**Issue by sbocconi** [reflow-project/weloop#103]
I tried to add a photo to a resource:

https://weloop.reflowproject.eu/resource/01FCT51592SSVQG8WC64GM5ZYC

This is the screenshot of the error message:

![Screenshot 2021-08-11 at 14 45 01](https://user-images.githubusercontent.com/3026280/129034044-d561f02b-159a-47dd-b533-db79a809fd78.png)

I tried with files of size 7.4 Mb, 2.1 Mb and 167 Kb.

**Comment by pral2a** [comment]
Image upload problems is a well known backend issue. You can see the backend issue we created https://github.com/dyne/zenpub/issues/54

**Comment by pral2a** [comment]
Duplicated see #79
