### ISSUE TITLE
New event on Resource window has Receiver field twice

### ISSUE THREAD

**Issue by sbocconi** [reflow-project/weloop#104]
It seems that the `Create a new event on resource` windows has twice the field `Receiver` iso having `Provider`

![Screenshot 2021-08-11 at 15 14 00](https://user-images.githubusercontent.com/3026280/129035335-47216fed-3ea8-48f6-80de-c5bbbef769ab.png)

**Comment by pral2a** [comment]
Already fixed a month ago and consolidated now via #149
