### ISSUE TITLE
Ownership of resource unclear on Material Passport page

### ISSUE THREAD

**Issue by sbocconi** [reflow-project/weloop#105]
On the page https://weloop.reflowproject.eu/resource/01FCT51592SSVQG8WC64GM5ZYC the resource has owner ocataco with quantity in stock: 0 kilo.

Questions:
1) Why is ocataco owner if there has been a transfer, and ocataco has zero left over? Why is not Stefano Bocconi owner?
2) If ocataco is owner, why if I am logged as Stefano Bocconi I can edit the resource and change the description of the resource, owned by ocataco?

**Comment by pral2a** [comment]
Yes, this is a backend related issue. We're post it here https://github.com/dyne/zenpub/issues/58

**Comment by sbocconi** [comment]
As I commented in the referenced back-end issue
>I am not clear why a new economicResource is created after a transfer?

>This does not sound in line with tracking a resources across a flow, I would think that a new resource is created only when particular events are performed, such as produce if I remember correctly.

Plus the fact that the old owner is still the owner of a zero quantity, does this make sense? There should be one owner and one resource at a given moment in time in a transfer (before and after).

**Comment by pral2a** [comment]
Fixed via #149 - When creating a new event on an existing resource now you can choose to create a new resource as a result or only to update the existing one. Previous behaviour will create a new resource on each event, leading users to confusing situation @sbocconi nicely described here.
