### ISSUE TITLE
Map page/component

### ISSUE THREAD

**Issue by kariyngva** [reflow-project/weloop#12]
To fully implement the map page and component we need answers to the following:

* Where to center the map?
On the wireframe it would appear the map is centered around a community location. As if right now I can't see that the [community object](https://frosty-torvalds-5060b3.netlify.app/api/community.doc.html) has such a field
* What are the map points on the map?
On the wireframe it is not clear what data should be fetched, be it [intents](https://frosty-torvalds-5060b3.netlify.app/docs/api_tour#look-for-intents-near-a-specific-location) or [resources](https://frosty-torvalds-5060b3.netlify.app/docs/api_tour#filter-resources-by-current-location)?

![image](https://user-images.githubusercontent.com/1204564/98443254-1ae81280-2102-11eb-80a6-66b4adb7f27d.png)

**Comment by pral2a** [comment]
> Where to center the map?

I suggest to implement in front-end the required geo function that centers and zooms the map to display all the available markers at a specific moment on time. That feature is particularly important if we start to add more filters in the future. In leaflet I always used that [approach](https://stackoverflow.com/questions/17277686/leaflet-js-center-the-map-on-a-group-of-markers).

> What are the map points on the map? On the wireframe it is not clear what data should be fetched, be it intents or resources?

At the we should moment map **resources** in there.

**Comment by pral2a** [comment]
> What are the map points on the map? On the wireframe it is not clear what data should be fetched, be it intents or resources?

@ivanminutillo confirms we should map **resources**. 

We also clarified **requests** are called **intents** in Reflow OS. Already updated other issues on that topics.

**Comment by kariyngva** [comment]
As discussed in the meeting between regarding the map other things. See details on [page 9 in the PDF](https://github.com/reflow-project/zenpub-client/issues/15).

* Component should list proposed intents
* Query for proposed intents and use GEO locations to create a leaflet bounding box to center around

**Comment by kariyngva** [comment]
I need test/seed data for me to finish implementing this component. The GraphQL endpoint seems to be void of any data.

The following query:

```
{ 
  communities {
    edges {
      id
    }
  }
  collections {
    edges {
      id
    }
  }
  intents {
    id
  }
  proposals {
    id
  }
  proposalsFiltered {
    id
  }
}
```
Returns: 
```js
{
{
  "data": {
    "collections": {
      "edges": []
    },
    "communities": {
      "edges": []
    },
    "intents": [],
    "proposals": [],
    "proposalsFiltered": []
  }
}
```

**Comment by ivanminutillo** [comment]
Hey @kariyngva, the staging server is now populated with seeds data to work with

**Comment by pral2a** [comment]
**All map views / components**

- [ ] Show proposed intents with pop-up with minal information (TBD) and link to the intent full single view
- [ ] Confirm map boundaries use proposed intents GEO locations to create a leaflet bounding box to center around

**Community specific view**

- [ ] Always filter by community as `specific scope` see [API](https://reflowos.dyne.org/docs/api_tour#look-for-proposals-with-a-specific-scope-eg-a-community) use of `inScopeOf` filters.
- [ ] Has dropdown to to filter by "specific category / taxonomy" see API[https://reflowos.dyne.org/docs/api_tour#look-for-all-proposals-tagged-with-a-specific-category--taxonomy] use of `tagIds` filters.
