### ISSUE TITLE
App visual consistency and branding

### ISSUE THREAD

**Issue by pral2a** [reflow-project/weloop#28]
- [ ] **WeLoop** branding. See [Reflow_OS_WeLoopBrand.pdf](https://github.com/reflow-project/zenpub-client/files/6142817/Reflow_OS_WeLoopBrand.pdf), ask design team @fablabbcn for the appropriate assets if needed
- [x] **Reflow** visual guidelines. See [Reflow_OS_StyleGuidelines.pdf](https://github.com/reflow-project/zenpub-client/files/6142816/Reflow_OS_StyleGuidelines.pdf). 
- [x] Check existing Reflow branded **Icons** in [Icons.zip](https://github.com/reflow-project/zenpub-client/files/6142819/Icons.zip) Spot other visuals needed to request the design team @fablabbcn.

Icons have been added under `/src/static/icons` but not implemented yet

**Comment by pral2a** [comment]
Fix icons in `#ff0000` color. Use `#02E379` or `#05244F` or `#333333` instead

![Screenshot 2021-05-25 at 11 38 38](https://user-images.githubusercontent.com/74249/119475878-d3e40680-bd4d-11eb-9482-85ec4f659518.png)

**Comment by viktorsmari** [comment]
@pral2a FYI the reason we use red icons, is that these pages have errors that need to be fixed.
Red is a  **temporary reminder** that the page needs fixing, or is not implemented yet.

The ones that are working are using `#333333`

As soon as the red ones have been implemented or fixed, their color will change to `#333`

**Comment by pral2a** [comment]
That’s perfect! Thank you very much for the clarification
