### ISSUE TITLE
Create a new Resource - location missing

### ISSUE THREAD

**Issue by viktorsmari** [reflow-project/weloop#88]
Is it possible to add a `location` when creating a new Resource?

Here it's missing:
![2021-06-15_20-24-34](https://user-images.githubusercontent.com/1689020/122104311-d6e78980-ce17-11eb-81e4-37e84d5095ce.png)

When we create an **intent** it is possible:
![2021-06-15_20-24-22](https://user-images.githubusercontent.com/1689020/122104315-d6e78980-ce17-11eb-81cf-4d6a5a3a4d39.png)

**Comment by pral2a** [comment]
Location should not only display a list of locations but allow to pick a location from the map and give it a name. Map search by geocoding the address is optional

Could you calculate the approximate time to implement, it?

**Comment by viktorsmari** [comment]
Implemented in pr #91
