### ISSUE TITLE
Comunties Economic Resource Inventory doesn't filter properly well

### ISSUE THREAD

**Issue by pral2a** [reflow-project/weloop#90]
Looks like **Economic Resources** linked to a particular **Community** are not filter properly. Both communities show the same list of  **Economic Resources**. 

See images:

![Screenshot 2021-06-21 at 12 48 58](https://user-images.githubusercontent.com/74249/122752800-ab3e2680-d291-11eb-8dcb-7e7a8152ac12.png)

![Screenshot 2021-06-21 at 13 06 21](https://user-images.githubusercontent.com/74249/122752790-a8dbcc80-d291-11eb-8622-1aa99866cbf6.png)

**Comment by viktorsmari** [comment]
Same as #61

**Comment by oksanasalohubova** [comment]
https://prnt.sc/18rue54 

`query community($communityId: ID) {
  economicResourcesFiltered(inScopeOf: [$communityId]) {
    id
    name
  }
}` 

This query does  not working for me
